
[cache._map]
":action" = 1

[_default]
controller = 'index'
action = 'index'

[_notFound]
controller = 'errors'
action = 'show404'
   
[dashboard.index]
pattern='/'

[dashboard._map]
":action" = 1

# '_list' indicates a list of method names 'list' is method listAction
[errors]
_list = ['index', 'show404', 'show505']

[menu.index]
methods = ['GET']

[menu.edit]

[menu.list]

[menu.item]
pattern = 'item/{id}'

[menu.link]

[menu.unlink]

[menu.subitem]

